name: dughri
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


# versions available, run `flutter pub outdated`.
dependencies:
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  device_preview: ^1.1.0
  dio: ^5.4.0
 
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  persistent_bottom_nav_bar: ^5.0.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_datepicker: ^24.1.45
  # Firebase 
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.4
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/Logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_assets:
  assets_path: assets/Images/
  output_path: lib/core/constant/
  filename: images_path.dart
  field_prefix: null
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
